default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: survey5_development

 
test:
  <<: *default
  database: survey5_test

production:
  <<: *default
  database: survey5_production
  username: survey5
  password: <%= ENV["SURVEY5_DATABASE_PASSWORD"] %>
